log:
  level: DEBUG

accessLog: {}

providers:
  file:
    directory: /etc/traefik/

entryPoints:
  web80:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web443
          scheme: https

  web443:
    address: ":443"
    http:
      tls:
        certResolver: acmeResolver

certificatesResolvers:
  acmeResolver:
    acme:
      email: novotnr0@gmail.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web
